export interface NakshatraDetails {
  id: number;
  name: string;
  gana: string;
  yoni: string;
  wruksha: string;
  pakshi: string;
  nadi: string;
}

export const nakshatraData: Record<number, NakshatraDetails> = {
  1: {
    id: 1,
    name: 'අස්විද',
    gana: 'දේව',
    yoni: 'අශ්ව',
    wruksha: 'ගොඩකදුරු',
    pakshi: 'භේරුණ්ඩ',
    nadi: 'ආදි',
  },
  2: {
    id: 2,
    name: 'බෙරණ',
    gana: 'මනුෂ්‍ය',
    yoni: 'ඇතා',
    wruksha: 'නුග',
    pakshi: 'කපුටා',
    nadi: 'මධ්‍ය',
  },
  3: {
    id: 3,
    name: 'කැති',
    gana: 'රාක්ෂ',
    yoni: 'එළු',
    wruksha: 'අත්තික්කා',
    pakshi: 'පිණිතුඩුවා',
    nadi: 'අන්ත්‍ය',
  },
  4: {
    id: 4,
    name: 'රෙහෙන',
    gana: 'මනුෂ්‍ය',
    yoni: 'නයා',
    wruksha: 'කුඹුක්',
    pakshi: 'බකමූණා',
    nadi: 'අන්ත්‍ය',
  },
  5: {
    id: 5,
    name: 'මුවසිරස',
    gana: 'දේව',
    yoni: 'සර්ප',
    wruksha: 'කිහිරි',
    pakshi: 'ගිරවා',
    nadi: 'මධ්‍ය',
  },
  6: {
    id: 6,
    name: 'අද',
    gana: 'මනුෂ්‍ය',
    yoni: 'බැල්ල',
    wruksha: 'අගිල්',
    pakshi: 'කණකොකා',
    nadi: 'ආදි',
  },
  7: {
    id: 7,
    name: 'පුනාවස',
    gana: 'දේව',
    yoni: 'බළලී',
    wruksha: 'උණ',
    pakshi: 'හංසයා',
    nadi: 'ආදි',
  },
  8: {
    id: 8,
    name: 'පුෂ',
    gana: 'දේව',
    yoni: 'එළු',
    wruksha: 'බෝ',
    pakshi: 'කපුටා',
    nadi: 'මධ්‍ය',
  },
  9: {
    id: 9,
    name: 'අස්ලිස',
    gana: 'රාක්ෂ',
    yoni: 'බළලා',
    wruksha: 'දොඹ',
    pakshi: 'මූණමාලිපා',
    nadi: 'අන්ත්‍ය',
  },
  10: {
    id: 10,
    name: 'මා',
    gana: 'රාක්ෂ',
    yoni: 'මීයා',
    wruksha: 'දඹ',
    pakshi: 'ගුරුළා',
    nadi: 'අන්ත්‍ය',
  },
  11: {
    id: 11,
    name: 'පුවපල්',
    gana: 'මනුෂ්‍ය',
    yoni: 'මී',
    wruksha: 'කෑල',
    pakshi: 'බකමූණා',
    nadi: 'මධ්‍ය',
  },
  12: {
    id: 12,
    name: 'උත්‍රපල්',
    gana: 'මනුෂ්‍ය',
    yoni: 'ගව',
    wruksha: 'ඇටඹ',
    pakshi: 'කණකොකා',
    nadi: 'ආදි',
  },
  13: {
    id: 13,
    name: 'හත',
    gana: 'දේව',
    yoni: 'මීහරක්',
    wruksha: 'ඇඹුල්ල',
    pakshi: 'ගිජුලිහිණියා',
    nadi: 'ආදි',
  },
  14: {
    id: 14,
    name: 'සිත',
    gana: 'රාක්ෂ',
    yoni: 'ව්‍යාඝ්‍ර',
    wruksha: 'බෙලි',
    pakshi: 'ගිරවා',
    nadi: 'මධ්‍ය',
  },
  15: {
    id: 15,
    name: 'සා',
    gana: 'දේව',
    yoni: 'මීහරක්',
    wruksha: 'කුඹුක්',
    pakshi: 'හංසයා',
    nadi: 'අන්ත්‍ය',
  },
  16: {
    id: 16,
    name: 'විසා',
    gana: 'රාක්ෂ',
    yoni: 'ව්‍යාඝ්‍ර',
    wruksha: 'මූණමල්',
    pakshi: 'කොබෙයියා',
    nadi: 'අන්ත්‍ය',
  },
  17: {
    id: 17,
    name: 'අනුර',
    gana: 'දේව',
    yoni: 'මුව',
    wruksha: 'මූණමල්',
    pakshi: 'මලිත්තා',
    nadi: 'මධ්‍ය',
  },
  18: {
    id: 18,
    name: 'දෙට',
    gana: 'රාක්ෂ',
    yoni: 'මුව',
    wruksha: 'හල්',
    pakshi: 'කණකොකා',
    nadi: 'ආදි',
  },
  19: {
    id: 19,
    name: 'මුල',
    gana: 'රාක්ෂ',
    yoni: 'සුනඛ',
    wruksha: 'සල්',
    pakshi: 'ගුරුළා',
    nadi: 'ආදි',
  },
  20: {
    id: 20,
    name: 'පුවසල',
    gana: 'මනුෂ්‍ය',
    yoni: 'වඳුරු',
    wruksha: 'වෙවැල්',
    pakshi: 'කපුටා',
    nadi: 'මධ්‍ය',
  },
  21: {
    id: 21,
    name: 'උතුරුසල',
    gana: 'මනුෂ්‍ය',
    yoni: 'මුගටි',
    wruksha: 'පනස',
    pakshi: 'පළඟැටියා',
    nadi: 'අන්ත්‍ය',
  },
  22: {
    id: 22,
    name: 'සුවණ',
    gana: 'දේව',
    yoni: 'වඳුරු',
    wruksha: 'වරා',
    pakshi: 'මයුර',
    nadi: 'අන්ත්‍ය',
  },
  23: {
    id: 23,
    name: 'දෙනට',
    gana: 'රාක්ෂ',
    yoni: 'සිංහ',
    wruksha: 'සමදරා',
    pakshi: 'ගුරුළා',
    nadi: 'මධ්‍ය',
  },
  24: {
    id: 24,
    name: 'සියාවස',
    gana: 'රාක්ෂ',
    yoni: 'අශ්ව',
    wruksha: 'කදඹ',
    pakshi: 'මොනරා',
    nadi: 'ආදි',
  },
  25: {
    id: 25,
    name: 'පුවපුටුප',
    gana: 'මනුෂ්‍ය',
    yoni: 'සිංහ',
    wruksha: 'අඹ',
    pakshi: 'ගිරවා',
    nadi: 'ආදි',
  },
  26: {
    id: 26,
    name: 'උත්‍රපුටුප',
    gana: 'මනුෂ්‍ය',
    yoni: 'ගව',
    wruksha: 'මී',
    pakshi: 'කෝකිල',
    nadi: 'මධ්‍ය',
  },
  27: {
    id: 27,
    name: 'රේවතී',
    gana: 'දේව',
    yoni: 'ඇතා',
    wruksha: 'මී',
    pakshi: 'මොනරා',
    nadi: 'අන්ත්‍ය',
  },
};
